### ISSUE TITLE
respoke background service ?

### ISSUE THREAD

**Issue by mFarghaly** [respoke/sample-respoke-android#2]
How to show Incoming call activity if my application is in the background ? or my mobile is closed ?

**Comment by chadxz** [comment]
we've got a push notification feature for that. You'll need to send an email to support@respoke.io to have it enabled on your account, as it is an unreleased feature. With push notifications enabled, you would receive a push like "Incoming call from Jane", where Jane is the endpointId of the caller. Upon foregrounding the app and the websocket connecting back up, the sdk will fire the call events.

Once push is enabled on your account, you'll be able to see the configuration options in the app config inside the developer portal.

Hope that helps! Let us know if you have further questions.

**Comment by mFarghaly** [comment]
Twilio for example has background service for Twilio Client and pending
activity that activated for incoming calls when phone is closed !
Can you release code something like this ?
It will be great for user experience.
Opening call from notification bar is bad or strange for millions of users
using Line, WhatsApp, FB Messenger ... etc daily.

**Comment by creslin287** [comment]
Right now, if you want to have a "persistent" connection using RespokeClient to Respoke, you have to implement your own background service for management of the RespokeClient instantiated object.

There are various tradeoffs to having semi-permanent background services up, and background services can still potentially be killed as well.

As @chadxz mentioned, the better way will be to use push notification support to obviate the need for a constantly running background service.

**Comment by jznadams** [comment]
We currently don't have example code for the specific use case you are talking about, but it could be accomplished with either push notifications (GCMS) or creating your own background service to interact with the Respoke SDK. The background service approach would allow you to be aware of incoming messages and calls more quickly, but there will be a trade-off with worse battery/CPU/memory performance for the device. Also, there is still a possibility that your background service could be terminated by the OS unexpectedly in some circumstances.

With push notifications, it's up to you to draw the UI that appears to the user in android. That could be a simple notification bar message, or it could be a full screen activity that looks like a traditional "incoming call" screen. In a few weeks we will be updating the sample application to demonstrate that second approach, but I don't have anything to give you today unfortunately. Regardless of whether you choose to run a background service or rely more heavily on push notifications, the part of your custom application that will handle displaying an "incoming call" screen to the user will be largely identical. We consider that an "application level feature", rather than something the SDK will handle itself.

**Comment by mFarghaly** [comment]
Thank you Chad and Jason, I will go with the background service solution.
